### ISSUE TITLE
Walk through

### ISSUE THREAD

**Issue by gavgrego** [sbehrends/Live-WorldCup-Notification-for-Slack#10]

**Comment by sbehrends** [comment]
Did you got it working?

First step is to create a Incoming webhook in Slack
https://aerolab.slack.com/services/new/incoming-webhook

You can host the script somewhere or even at your own computer, but something like heroku is recommended because this specific project uses 1 worker and that is free.
Customize the setting (by code or with env. vars) and run it.

Thats all :)

**Comment by sbehrends** [comment]
Oh... and if using heroku its important to set a worker

```
heroku ps:scale worker=1
```
